# Generated by Django 6.0.2 on 2026-04-17 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(blank=True, max_length=50, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("localidad", models.CharField(blank=True, max_length=50, null=True)),
                ("direccion", models.CharField(blank=True, max_length=100, null=True)),
                ("factura_produccion", models.BooleanField(default=False)),
                ("cuit", models.CharField(blank=True, max_length=15, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "clientes",
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "categoria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Miel", "Miel"),
                            ("Alimento", "Alimento"),
                            ("Cera", "Cera"),
                            ("Madera", "Madera"),
                            ("Estampa", "Estampa"),
                            ("Insumos", "Insumos"),
                            ("Medicamentos", "Medicamentos"),
                            ("Otros", "Otros"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=0)),
                ("cantidad_vendida", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "productos",
            },
        ),
        migrations.CreateModel(
            name="Operacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("activa", models.BooleanField(default=True)),
                (
                    "observaciones",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "monto_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "valor_dolar",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "valor_kilo_miel",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        db_column="id_cliente",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.cliente",
                    ),
                ),
            ],
            options={
                "db_table": "operaciones",
            },
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "medio_pago",
                    models.CharField(
                        choices=[
                            ("Efectivo", "Efectivo"),
                            ("Transferencia", "Transferencia"),
                            ("Debito", "Debito"),
                        ],
                        max_length=50,
                    ),
                ),
                ("monto", models.IntegerField()),
                (
                    "operacion",
                    models.ForeignKey(
                        db_column="id_operacion",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.operacion",
                    ),
                ),
            ],
            options={
                "db_table": "pagos",
            },
        ),
        migrations.CreateModel(
            name="DetalleOperacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "operacion",
                    models.ForeignKey(
                        db_column="id_operacion",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.operacion",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        db_column="id_producto",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.producto",
                    ),
                ),
            ],
            options={
                "db_table": "detalle_operaciones",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("operacion", "producto"),
                        name="unique_operacion_producto",
                    )
                ],
            },
        ),
    ]
