# Generated by Django 6.0.2 on 2026-04-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pago",
            name="medio_pago",
        ),
    ]
