# Generated by Django 6.0.2 on 2026-05-06 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_pago_medio_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operacion',
            options={'verbose_name_plural': 'Operaciones'},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterField(
            model_name='detalleoperacion',
            name='producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='main.producto'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
