# Generated by Django 6.0.2 on 2026-05-06 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_operacion_options_alter_pago_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='detalleoperacion',
            name='unique_operacion_producto',
        ),
    ]
