# Generated by Django 6.0.2 on 2026-05-06 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_detalleoperacion_unique_operacion_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleoperacion',
            name='producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='main.producto'),
        ),
        migrations.AddConstraint(
            model_name='detalleoperacion',
            constraint=models.UniqueConstraint(fields=('operacion', 'producto'), name='unique_operacion_producto'),
        ),
    ]
