# Generated by Django 6.0.2 on 2026-05-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_detalleoperacion_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Miel', 'Miel'), ('Alimento', 'Alimento'), ('Cera', 'Cera'), ('Madera', 'Madera'), ('Estampado', 'Estampado'), ('Insumos', 'Insumos'), ('Medicamentos', 'Medicamentos'), ('Otros', 'Otros')], max_length=50, null=True),
        ),
    ]
