# Generated by Django 6.0.2 on 2026-05-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cotizaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choferes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('total_viajes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'choferes',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('patente', models.CharField(max_length=7)),
                ('total_viajes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'vehiculos',
            },
        ),
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_caja', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_vuelta', models.DateTimeField(blank=True, null=True)),
                ('gastos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_caja', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'viajes',
            },
        ),
    ]
