# Generated by Django 6.0.2 on 2026-05-19 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_choferes_vehiculo_viajes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Viajes',
            new_name='Viaje',
        ),
        migrations.RenameModel(
            old_name='Choferes',
            new_name='Chofer',
        ),
        migrations.AddField(
            model_name='viaje',
            name='chofer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.chofer'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.vehiculo'),
        ),
    ]
