# Generated by Django 6.0.2 on 2026-05-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_viaje_delete_viajes_rename_choferes_chofer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='chofer',
            constraint=models.UniqueConstraint(fields=('nombre', 'apellido'), name='unique_nombre_apellido_chofer'),
        ),
    ]
