# Generated by Django 6.0.2 on 2026-05-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_producto_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='destino',
            field=models.CharField(default='', max_length=30),
        ),
    ]
