# Generated by Django 6.0.2 on 2026-04-06 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_remito'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='operacion',
            field=models.ForeignKey(blank=True, db_column='id_operacion', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.operacion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='pagos',
            table='pagos',
        ),
    ]
