# Generated by Django 6.0.2 on 2026-04-16 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_pagos_operacion_alter_producto_cantidad_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "medio_pago",
                    models.CharField(
                        choices=[
                            ("Efectivo", "Efectivo"),
                            ("Transferencia", "Transferencia"),
                            ("Debito", "Debito"),
                        ],
                        max_length=50,
                    ),
                ),
                ("monto", models.IntegerField()),
                (
                    "operacion",
                    models.ForeignKey(
                        db_column="id_operacion",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.operacion",
                    ),
                ),
            ],
            options={
                "db_table": "pagos",
            },
        ),
        migrations.DeleteModel(
            name="Pagos",
        ),
    ]
