# Generated by Django 6.0.2 on 2026-05-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_chofer_activo_vehiculo_activo_viaje_destino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='final_caja',
        ),
    ]
