# Generated by Django 6.0.2 on 2026-04-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_pago_delete_pagos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operacion",
            name="metodo_de_pago",
        ),
        migrations.AddField(
            model_name="operacion",
            name="activa",
            field=models.BooleanField(default=True),
        ),
    ]
