# Generated by Django 6.0.2 on 2026-05-26 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_viaje_final_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='chofer',
            field=models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, to='main.chofer'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='vehiculo',
            field=models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.PROTECT, to='main.vehiculo'),
        ),
    ]
