# Generated by Django 6.0.2 on 2026-05-26 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_viaje_chofer_alter_viaje_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='chofer',
            field=models.ForeignKey(db_column='id_chofer', on_delete=django.db.models.deletion.PROTECT, to='main.chofer'),
        ),
    ]
