# Generated by Django 6.0.2 on 2026-05-28 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_viaje_chofer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='destino',
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='fecha_vuelta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DetalleViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=30)),
                ('viaje', models.ForeignKey(db_column='id_viaje', on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='main.viaje')),
            ],
            options={
                'db_table': 'detalle_viajes',
            },
        ),
    ]
