# Generated by Django 6.0.2 on 2026-05-30 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_viaje_destino_alter_vehiculo_patente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='cliente',
            field=models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, to='main.cliente'),
        ),
    ]
