# Generated by Django 6.0.2 on 2026-06-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_operacion_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
