# Generated by Django 6.0.2 on 2026-06-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_viaje_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizaciones',
            name='monto',
            field=models.IntegerField(default=0),
        ),
    ]
