# Generated by Django 6.0.2 on 2026-06-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_cotizaciones_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizaciones',
            name='monto',
            field=models.IntegerField(default=1),
        ),
    ]
