# Generated by Django 6.0.2 on 2026-06-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_cotizaciones_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='gastos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='inicio_caja',
            field=models.IntegerField(default=0),
        ),
    ]
