# Generated by Django 6.0.2 on 2026-06-03 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_viaje_gastos_alter_viaje_inicio_caja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='gastos',
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasto', models.CharField(choices=[('Comida', 'Comida'), ('Combustible', 'Combustible'), ('Estacionamiento', 'Estacionamiento')], max_length=25)),
                ('monto', models.IntegerField(default=0)),
                ('viaje', models.ForeignKey(db_column='id_viaje', on_delete=django.db.models.deletion.CASCADE, related_name='detalle_gastos', to='main.viaje')),
            ],
            options={
                'db_table': 'gastos',
            },
        ),
    ]
