# Generated by Django 6.0.2 on 2026-06-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_viaje_gastos_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='gasto',
            field=models.CharField(choices=[('Comida', 'Comida'), ('Combustible', 'Combustible'), ('Playa', 'Playa'), ('Peaje', 'Peaje'), ('Hotel', 'Hotel'), ('Viaticos personales', 'Viaticos personales'), ('Extras', 'Extras')], max_length=25),
        ),
    ]
