# Generated by Django 6.0.2 on 2026-06-05 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_gasto_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='viaje',
            field=models.ForeignKey(blank=True, db_column='id_viaje', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operaciones', to='main.viaje'),
        ),
    ]
