# Generated by Django 6.0.2 on 2026-06-05 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_operacion_viaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacion',
            name='observaciones',
        ),
    ]
