# Generated by Django 6.0.2 on 2026-06-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_operacion_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacion',
            name='monto_total',
        ),
        migrations.AddField(
            model_name='detalleoperacion',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='operacion',
            name='tipo_operacion',
            field=models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], default='venta', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad_comprada',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
