# Generated by Django 6.0.2 on 2026-06-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_operacion_monto_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleoperacion',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='tipo_operacion',
            field=models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], max_length=10),
        ),
    ]
