# Generated by Django 6.0.2 on 2026-06-08 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_detalleoperacion_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chofer',
            options={'verbose_name_plural': 'Choferes'},
        ),
        migrations.AlterModelOptions(
            name='cotizaciones',
            options={'verbose_name_plural': 'Cotizaciones'},
        ),
    ]
