# Generated by Django 6.0.2 on 2026-06-18 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_gasto_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chofer',
            name='total_viajes',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='total_viajes',
        ),
    ]
