# Generated by Django 6.0.2 on 2026-06-22 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_chofer_total_viajes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViajeReparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_viaje_reparto', models.DateField()),
                ('gasto_combustible_viaje_reparto', models.IntegerField(default=0)),
                ('chofer', models.ForeignKey(db_column='id_chofer', on_delete=django.db.models.deletion.PROTECT, to='main.chofer')),
                ('vehiculo', models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.PROTECT, to='main.vehiculo')),
            ],
            options={
                'db_table': 'viaje_reparto',
            },
        ),
        migrations.CreateModel(
            name='DetalleViajeReparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinos_reparto', models.CharField(max_length=30)),
                ('viaje_reparto', models.ForeignKey(db_column='id_viajereparto', on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='main.viajereparto')),
            ],
            options={
                'db_table': 'detalle_viaje_reparto',
            },
        ),
    ]
