# Generated by Django 6.0.2 on 2026-06-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_viajereparto_detalleviajereparto'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajereparto',
            name='empleado_costo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='viajereparto',
            name='valor_viaje',
            field=models.IntegerField(default=0),
        ),
    ]
