# Generated by Django 6.0.2 on 2026-06-24 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_rename_empleado_costo_viajereparto_costo_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleViajeCereal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='viajereparto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ViajeCereal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_viaje_cereal', models.DateField()),
                ('tipo_cereal', models.CharField(blank=True, choices=[('Maiz', 'Maiz'), ('Soja', 'Soja'), ('Trigo', 'Trigo')], max_length=50, null=True)),
                ('codigo_trazabilidad_granos', models.IntegerField(default=0)),
                ('toneladas', models.IntegerField(default=0)),
                ('precio_tonelada', models.IntegerField(default=0)),
                ('porcentaje_chofer', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('chofer', models.ForeignKey(db_column='id_chofer', on_delete=django.db.models.deletion.PROTECT, to='main.chofer')),
                ('vehiculo', models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.PROTECT, to='main.vehiculo')),
            ],
            options={
                'db_table': 'viaje_cereal',
            },
        ),
    ]
