# Generated by Django 6.0.2 on 2026-06-25 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_viajecereal_campos_detalleviajecereal_destinos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viajecereal',
            options={'verbose_name': 'Viaje cereal', 'verbose_name_plural': 'Viajes cereales'},
        ),
        migrations.AddField(
            model_name='viajecereal',
            name='cliente',
            field=models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viajes_cereales', to='main.cliente'),
        ),
        migrations.AlterField(
            model_name='viajecereal',
            name='tipo_cereal',
            field=models.CharField(choices=[('Maiz', 'Maiz'), ('Soja', 'Soja'), ('Trigo', 'Trigo'), ('Mani', 'Mani')], max_length=50),
        ),
        migrations.CreateModel(
            name='GastoViajeCereal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasto', models.CharField(choices=[('Comida', 'Comida'), ('Combustible', 'Combustible'), ('Playa', 'Playa'), ('Peaje', 'Peaje'), ('Hotel', 'Hotel'), ('Viaticos personales', 'Viaticos personales'), ('Extras', 'Extras')], max_length=25)),
                ('monto', models.IntegerField(default=0)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('viaje_cereal', models.ForeignKey(db_column='id_viajecereal', on_delete=django.db.models.deletion.CASCADE, related_name='detalle_gastos', to='main.viajecereal')),
            ],
            options={
                'db_table': 'gastos_viaje_cereal',
            },
        ),
    ]
