# Generated by Django 6.0.2 on 2026-06-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_viajecereal_options_viajecereal_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajecereal',
            name='codigo_trazabilidad_granos',
            field=models.CharField(max_length=15),
        ),
    ]
