# Generated by Django 6.0.2 on 2026-06-27 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_viajecereal_codigo_trazabilidad_granos'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoViajeReparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasto', models.CharField(choices=[('Comida', 'Comida'), ('Combustible', 'Combustible'), ('Playa', 'Playa'), ('Peaje', 'Peaje'), ('Hotel', 'Hotel'), ('Viaticos personales', 'Viaticos personales'), ('Extras', 'Extras')], max_length=25)),
                ('monto', models.IntegerField(default=0)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('viaje_reparto', models.ForeignKey(db_column='id_viajereparto', on_delete=django.db.models.deletion.CASCADE, related_name='detalle_gastos', to='main.viajereparto')),
            ],
            options={
                'db_table': 'gastos_viaje_reparto',
            },
        ),
    ]
