# Generated by Django 6.0.2 on 2026-07-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_gastoviajereparto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotizaciones',
            name='monto',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
