# Generated by Django 6.0.2 on 2026-07-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_cotizaciones_cantidad_alter_cotizaciones_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='monto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gastoviajecereal',
            name='monto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gastoviajereparto',
            name='monto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='inicio_caja',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='viajecereal',
            name='porcentaje_chofer',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='viajecereal',
            name='precio_tonelada',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='viajecereal',
            name='toneladas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='viajereparto',
            name='costo_empleado',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='viajereparto',
            name='gasto_combustible_viaje_reparto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='viajereparto',
            name='valor_viaje',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
