# Generated by Django 6.0.2 on 2026-07-07 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_gasto_monto_alter_gastoviajecereal_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleoperacion',
            name='cotizacion',
            field=models.ForeignKey(blank=True, db_column='id_cotizacion', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.cotizaciones'),
        ),
        migrations.AlterField(
            model_name='detalleoperacion',
            name='producto',
            field=models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.producto'),
        ),
        migrations.AddConstraint(
            model_name='detalleoperacion',
            constraint=models.UniqueConstraint(fields=('operacion', 'cotizacion'), name='unique_operacion_cotizacion'),
        ),
        migrations.AddConstraint(
            model_name='detalleoperacion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cotizacion__isnull', True), ('producto__isnull', False)), models.Q(('cotizacion__isnull', False), ('producto__isnull', True)), _connector='OR'), name='detalle_producto_o_cotizacion'),
        ),
    ]
