# Generated by Django 6.0.2 on 2026-07-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_detalleoperacion_cotizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='valor_kilo_cera',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
