# Generated by Django 6.0.2 on 2026-07-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_operacion_valor_kilo_cera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Miel', 'Miel'), ('Alimento', 'Alimento'), ('Cera', 'Cera'), ('Madera', 'Madera'), ('Estampado', 'Estampado'), ('Insumos', 'Insumos'), ('Medicamentos', 'Medicamentos'), ('Tambores Vacios', 'Tambores Vacios'), ('Otros', 'Otros')], max_length=50, null=True),
        ),
    ]
