# Generated by Django 6.0.2 on 2026-07-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajecereal',
            name='toneladas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
