# Generated by Django 6.0.2 on 2026-07-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_operacion_fecha_alter_pago_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='observaciones',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
