# Generated by Django 6.0.2 on 2026-07-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_operacion_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajecereal',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='viajereparto',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
