# Generated by Django 6.0.2 on 2026-07-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_viajecereal_pagado_viajereparto_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajecereal',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viajereparto',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
