# Generated by Django 6.0.2 on 2026-07-22 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_viajecereal_fecha_pago_viajereparto_fecha_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinoViajeReparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad_destino', models.CharField(max_length=60, unique=True)),
                ('valor_viaje', models.PositiveIntegerField(default=0)),
                ('cant_viajes', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'destino_viaje_reparto',
                'ordering': ['localidad_destino'],
            },
        ),
        migrations.AddField(
            model_name='viajereparto',
            name='destino',
            field=models.ForeignKey(blank=True, db_column='id_destino', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='main.destinoviajereparto'),
        ),
    ]
