# Generated by Django 6.0.2 on 2026-07-23 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_poblar_catalogo_destinos_reparto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chofer',
            new_name='Empleado',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='chofer',
            new_name='empleado',
        ),
        migrations.RenameField(
            model_name='viajereparto',
            old_name='chofer',
            new_name='empleado',
        ),
        migrations.RenameField(
            model_name='viajecereal',
            old_name='chofer',
            new_name='empleado',
        ),
        migrations.RenameField(
            model_name='viajecereal',
            old_name='porcentaje_chofer',
            new_name='porcentaje_empleado',
        ),
    ]
