# Generated by Django 6.0.2 on 2026-07-23 20:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20260723_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagosEmpleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Pagos de Empleados',
                'db_table': 'pagos_empleados',
            },
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name_plural': 'Empleados'},
        ),
        migrations.RemoveConstraint(
            model_name='empleado',
            name='unique_nombre_apellido_chofer',
        ),
        migrations.AddField(
            model_name='empleado',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='empleado',
            field=models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.PROTECT, to='main.empleado'),
        ),
        migrations.AlterField(
            model_name='viajecereal',
            name='empleado',
            field=models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.PROTECT, to='main.empleado'),
        ),
        migrations.AlterField(
            model_name='viajereparto',
            name='empleado',
            field=models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.PROTECT, to='main.empleado'),
        ),
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.UniqueConstraint(fields=('nombre', 'apellido'), name='unique_nombre_apellido_empleado'),
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='empleados',
        ),
        migrations.AddField(
            model_name='pagosempleados',
            name='empleado',
            field=models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='main.empleado'),
        ),
    ]
