# Generated by Django 6.0.2 on 2026-07-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_pagosempleados_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosempleados',
            name='observaciones',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
