# Generated by Django 6.0.2 on 2026-07-27 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_pagosempleados_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='saldo',
        ),
    ]
