# Generated by Django 6.0.2 on 2026-07-31 21:29

import django.db.models.deletion
import django.utils.timezone
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_remove_empleado_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=60, null=True)),
                ('localidad', models.CharField(blank=True, max_length=60, null=True)),
                ('direccion', models.CharField(blank=True, max_length=120, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('comision_inmobiliaria', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alquilada', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Casas',
                'db_table': 'casas',
                'ordering': ['nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PagoAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('periodo', models.DateField(default=main.models.periodo_actual)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('casa', models.ForeignKey(db_column='id_casa', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='main.casa')),
            ],
            options={
                'verbose_name_plural': 'Pagos de alquileres',
                'db_table': 'pagos_alquileres',
                'ordering': ['-periodo', '-fecha', '-id'],
                'indexes': [models.Index(fields=['casa', 'periodo'], name='idx_pago_alquiler_casa_periodo')],
            },
        ),
    ]
