# Generated by Django 6.0.2 on 2026-08-02 03:43

from django.db import migrations, models
from django.db.models import Count


def unificar_pagos_del_mismo_mes(apps, schema_editor):
    """Deja un solo pago por casa y mes antes de imponer la restriccion unica.

    Los pagos cargados hasta ahora podian ser parciales, asi que una casa puede
    tener varios del mismo mes. No los borro: sumo los montos en uno solo, que es
    lo que ese mes se termino cobrando, y le dejo la fecha del ultimo, que es
    cuando el alquiler quedo saldado. Asi no se pierde plata al migrar.
    """
    PagoAlquiler = apps.get_model("main", "PagoAlquiler")

    repetidos = (
        PagoAlquiler.objects.values("casa", "periodo")
        .annotate(cantidad=Count("id"))
        .filter(cantidad__gt=1)
    )

    for grupo in repetidos:
        pagos = list(
            PagoAlquiler.objects.filter(casa=grupo["casa"], periodo=grupo["periodo"])
            .order_by("fecha", "id")
        )
        sobreviviente = pagos[-1]
        sobreviviente.monto = sum(pago.monto for pago in pagos)
        sobreviviente.save(update_fields=["monto"])

        PagoAlquiler.objects.filter(
            id__in=[pago.id for pago in pagos[:-1]]
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_casa_pagoalquiler'),
    ]

    operations = [
        # La unificacion va primero: con duplicados en la tabla, la restriccion
        # no se puede crear. migrations.RunPython.noop al revertir, porque los
        # pagos que se unificaron no se pueden volver a separar.
        migrations.RunPython(unificar_pagos_del_mismo_mes, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name='pagoalquiler',
            name='idx_pago_alquiler_casa_periodo',
        ),
        migrations.AddConstraint(
            model_name='pagoalquiler',
            constraint=models.UniqueConstraint(fields=('casa', 'periodo'), name='unique_pago_alquiler_casa_periodo'),
        ),
    ]
