# Generated by Django 6.0.2 on 2026-08-02 06:03

import django.utils.timezone
from django.db import migrations, models
from django.db.models import Min


def retroceder_alta_hasta_el_primer_pago(apps, schema_editor):
    """Da de alta cada casa en su pago mas viejo, no el dia de la migracion.

    El campo entra con default de hoy, y dejarlo asi borraria de un plumazo
    todos los meses anteriores: ninguna casa "existiria" antes de hoy y los
    meses viejos aparecerian vacios pese a tener pagos cargados.

    El pago mas antiguo es la unica prueba que tiene el sistema de que la casa
    ya se administraba en esa fecha, asi que se usa como alta. Las casas sin
    ningun pago se quedan con hoy: no hay con que contradecirlo, y el usuario
    puede corregir la fecha desde el panel de la casa.
    """
    Casa = apps.get_model("main", "Casa")

    casas = Casa.objects.annotate(primer_pago=Min("pagos__periodo")).filter(
        primer_pago__isnull=False
    )
    for casa in casas:
        if casa.primer_pago < casa.fecha_alta:
            casa.fecha_alta = casa.primer_pago
            casa.save(update_fields=["fecha_alta"])


def volver_atras(apps, schema_editor):
    # El campo se borra entero al revertir, no hay nada que restaurar
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_remove_pagoalquiler_idx_pago_alquiler_casa_periodo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='fecha_alta',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.RunPython(retroceder_alta_hasta_el_primer_pago, volver_atras),
    ]
