# Generated by Django 6.0.2 on 2026-08-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    """Saca el blank del fin del contrato para que el admin tambien lo exija.

    Solo toca la validacion de los formularios, no la tabla: la columna sigue
    aceptando null porque los contratos que trajo la migracion 0058 desde la
    tabla de casas quedaron sin vencimiento y todavia hay que cargarselo.
    """

    dependencies = [
        ('main', '0058_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fin',
            field=models.DateField(null=True),
        ),
    ]
