# Generated by Django 6.0.2 on 2026-08-03 21:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_alter_contrato_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoCasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('categoria', models.CharField(choices=[('Impuestos', 'Impuestos'), ('Tasas municipales', 'Tasas municipales'), ('Mantenimiento', 'Mantenimiento'), ('Servicios', 'Servicios'), ('Seguro', 'Seguro'), ('Otros', 'Otros')], max_length=30)),
                ('detalle', models.CharField(blank=True, max_length=120, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('casa', models.ForeignKey(db_column='id_casa', on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='main.casa')),
            ],
            options={
                'verbose_name': 'Gasto de casa',
                'verbose_name_plural': 'Gastos de casas',
                'db_table': 'gastos_casas',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
