# Generated by Django 6.0.2 on 2026-08-03 22:50

from django.db import migrations, models


def redondear_contratos(apps, schema_editor):
    """Saca los centavos antes de que la columna deje de tener decimales.

    El ALTER de MySQL redondearia solo, pero con una advertencia y sin dejar
    rastro de que paso. Redondeando aca el dato queda igual antes y despues, y
    la conversion de tipo no tiene nada que decidir.
    """
    Contrato = apps.get_model("main", "Contrato")
    for contrato in Contrato.objects.all():
        contrato.monto_mensual = round(contrato.monto_mensual)
        if contrato.comision_inmobiliaria is not None:
            contrato.comision_inmobiliaria = round(contrato.comision_inmobiliaria)
        contrato.save(update_fields=["monto_mensual", "comision_inmobiliaria"])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_gastocasa'),
    ]

    operations = [
        migrations.RunPython(redondear_contratos, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='contrato',
            name='comision_inmobiliaria',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='monto_mensual',
            field=models.PositiveIntegerField(),
        ),
    ]
