# Generated by Django 6.0.2 on 2026-08-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_alter_contrato_comision_inmobiliaria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstacionDeServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estacion de servicio',
                'verbose_name_plural': 'Estaciones de servicio',
                'db_table': 'estaciones_de_servicio',
                'ordering': ['nombre', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='pagoalquiler',
            options={'ordering': ['-periodo', '-fecha', '-id'], 'verbose_name': 'Pago de alquiler', 'verbose_name_plural': 'Pagos de alquileres'},
        ),
    ]
