# Generated by Django 6.0.2 on 2026-08-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_estaciondeservicio_alter_pagoalquiler_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinoviajereparto',
            name='valor_viaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='viajereparto',
            name='valor_viaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
