# Generated by Django 6.0.2 on 2026-08-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_alter_destinoviajereparto_valor_viaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='sueldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
