# Generated by Django 6.0.2 on 2026-08-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_empleado_sueldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='inicio_cuenta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
