# Generated by Django 6.0.2 on 2026-08-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_empleado_inicio_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajecereal',
            name='dadora_carga',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='viajecereal',
            name='dadora_tipo_cobro',
            field=models.CharField(blank=True, choices=[('porcentaje', 'Porcentaje'), ('tonelada', 'Por tonelada')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='viajecereal',
            name='dadora_valor',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
