# Generated by Django 6.0.2 on 2026-08-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_viajecereal_dadora_carga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajecereal',
            name='dadora_tipo_cobro',
            field=models.CharField(blank=True, choices=[('porcentaje', 'Porcentaje'), ('tonelada', 'Por tonelada'), ('efectivo', 'Efectivo')], default='', max_length=20),
        ),
    ]
