# Generated by Django 6.0.2 on 2026-08-07 18:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_alter_viajecereal_dadora_tipo_cobro'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroKilometraje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('kilometros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehiculo', models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.CASCADE, related_name='registros_km', to='main.vehiculo')),
            ],
            options={
                'verbose_name': 'Registro de kilometraje',
                'verbose_name_plural': 'Registros de kilometraje',
                'db_table': 'registros_kilometraje',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('vehiculo', models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.CASCADE, related_name='seguros', to='main.vehiculo')),
            ],
            options={
                'verbose_name': 'Seguro',
                'verbose_name_plural': 'Seguros',
                'db_table': 'seguros',
                'ordering': ['-fin', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Servis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('vehiculo', models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='main.vehiculo')),
            ],
            options={
                'verbose_name': 'Servis',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicios',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('vehiculo', models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.CASCADE, related_name='vtvs', to='main.vehiculo')),
            ],
            options={
                'verbose_name': 'VTV',
                'verbose_name_plural': 'VTV',
                'db_table': 'vtv',
                'ordering': ['-fin', '-id'],
            },
        ),
    ]
