# Generated by Django 6.0.2 on 2026-08-07 20:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_registrokilometraje_seguro_servis_vtv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('texto', models.CharField(max_length=250)),
                ('vehiculo', models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='main.vehiculo')),
            ],
            options={
                'verbose_name': 'Observación de vehículo',
                'verbose_name_plural': 'Observaciones de vehículos',
                'db_table': 'observaciones_vehiculo',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
