# Generated by Django 6.0.2 on 2026-08-10 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_observacionvehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pagada', models.BooleanField(default=False)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='main.estaciondeservicio')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas_combustible', to='main.vehiculo')),
            ],
            options={
                'verbose_name': 'Carga de combustible',
                'verbose_name_plural': 'Cargas de combustible',
                'db_table': 'cargas_combustible',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
