# Generated by Django 6.0.2 on 2026-08-10 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_cargacombustible'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargacombustible',
            name='empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cargas_combustible', to='main.empleado'),
            preserve_default=False,
        ),
    ]
