# Generated by Django 6.0.2 on 2026-08-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_cargacombustible_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargacombustible',
            name='litros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
