# Generated by Django 6.0.2 on 2026-08-10 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_cargacombustible_litros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargacombustible',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='cargacombustible',
            name='viaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargas_combustible', to='main.viaje'),
        ),
        migrations.AddField(
            model_name='cargacombustible',
            name='viaje_cereal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargas_combustible', to='main.viajecereal'),
        ),
        migrations.AddField(
            model_name='cargacombustible',
            name='viaje_reparto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargas_combustible', to='main.viajereparto'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='carga_combustible',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_gasto', to='main.cargacombustible'),
        ),
        migrations.AddField(
            model_name='gastoviajecereal',
            name='carga_combustible',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_gasto', to='main.cargacombustible'),
        ),
        migrations.AddField(
            model_name='gastoviajereparto',
            name='carga_combustible',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_gasto', to='main.cargacombustible'),
        ),
    ]
