# Generated by Django 6.0.2 on 2026-08-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_remove_cargacombustible_observaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='vencimiento_carnet',
            field=models.DateField(blank=True, null=True),
        ),
    ]
