# Generated by Django 6.0.2 on 2026-08-13 22:31

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_empleado_vencimiento_carnet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
                'ordering': ['nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OperacionIva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra')], max_length=10)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('monto_neto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('alicuota', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5)),
                ('detalle', models.CharField(blank=True, max_length=120, null=True)),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to='main.empresa')),
            ],
            options={
                'verbose_name': 'Operacion de IVA',
                'verbose_name_plural': 'Operaciones de IVA',
                'db_table': 'operaciones_iva',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
