# Generated by Django 6.0.2 on 2026-08-14 16:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_empresa_operacioniva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Bancos',
                'db_table': 'bancos',
                'ordering': ['nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CuentaCorriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40)),
                ('activa', models.BooleanField(default=True)),
                ('banco', models.ForeignKey(db_column='id_banco', on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_corrientes', to='main.banco')),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_corrientes', to='main.empresa')),
            ],
            options={
                'verbose_name': 'Cuenta corriente',
                'verbose_name_plural': 'Cuentas corrientes',
                'db_table': 'cuentas_corrientes',
                'ordering': ['banco__nombre', 'numero', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('a_cobrar', 'A cobrar'), ('a_pagar', 'A pagar')], max_length=10)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_cobro', models.DateField()),
                ('concepto', models.CharField(max_length=250)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cuenta_corriente', models.ForeignKey(db_column='id_cuenta_corriente', on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='main.cuentacorriente')),
            ],
            options={
                'verbose_name': 'Cheque',
                'verbose_name_plural': 'Cheques',
                'db_table': 'cheques',
                'ordering': ['fecha_cobro', 'id'],
            },
        ),
    ]
