# Generated by Django 6.0.2 on 2026-08-14 22:39

from django.db import migrations


def borrar_cheques_a_cobrar(apps, schema_editor):
    """Los cheques ahora son siempre a pagar: los 'a cobrar' cargados eran de
    prueba, asi que se eliminan antes de quitar la columna tipo."""
    Cheque = apps.get_model("main", "Cheque")
    Cheque.objects.filter(tipo="a_cobrar").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_banco_cuentacorriente_cheque'),
    ]

    operations = [
        migrations.RunPython(borrar_cheques_a_cobrar, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='cheque',
            name='tipo',
        ),
    ]
