# Generated by Django 6.0.2 on 2026-08-18 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_remove_cheque_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('monto', models.PositiveIntegerField(default=0)),
                ('viaje', models.ForeignKey(db_column='id_viaje', on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_caja', to='main.viaje')),
            ],
            options={
                'db_table': 'ingresos_caja',
            },
        ),
    ]
