# Generated by Django 6.0.2 on 2026-08-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_ingresocaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='cobrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cheque',
            name='numero',
            field=models.CharField(default='', max_length=20),
        ),
    ]
