# Generated by Django 6.0.2 on 2026-08-19 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_cheque_cobrado_cheque_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosempleados',
            name='origen',
            field=models.CharField(choices=[('manual', 'Manual'), ('devolucion', 'Devolución de caja')], default='manual', max_length=15),
        ),
        migrations.AddField(
            model_name='viaje',
            name='devolucion_estado',
            field=models.CharField(blank=True, choices=[('', 'Sin registrar'), ('total', 'Devolvió todo'), ('parcial', 'Devolvió una parte')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='viaje',
            name='monto_devuelto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='viaje',
            name='pago_devolucion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viaje_devolucion', to='main.pagosempleados'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='sobrante_devolucion',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
