# Generated by Django 6.0.2 on 2026-09-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_rename_cotizaciones_productoporkg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleviaje',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='detalleviajecereal',
            options={'ordering': ['id']},
        ),
    ]
