# Generated by Django 6.0.2 on 2026-09-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_alter_detalleviaje_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajecereal',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
