# Generated by Django 6.0.2 on 2026-09-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_viajecereal_numero_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoporkg',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productoporkg',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Miel', 'Miel'), ('Alimento', 'Alimento'), ('Cera', 'Cera'), ('Madera', 'Madera'), ('Estampado', 'Estampado'), ('Insumos', 'Insumos'), ('Medicamentos', 'Medicamentos'), ('Tambores Vacios', 'Tambores Vacios'), ('Otros', 'Otros')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productoporkg',
            name='articulo',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
