# Generated by Django 6.0.2 on 2026-09-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_poblar_categoria_productos_por_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='mostrar_en_inicio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productoporkg',
            name='mostrar_en_inicio',
            field=models.BooleanField(default=False),
        ),
    ]
